#!/usr/bin/env bash

export CONTECO_LABEL="ksqldb-cli.base - Conteco "
export CONTECO_DESCRIPTION="Confluent ksqlDB CLI base image, using default configuration."

export CONTECO_TYPE="ksqldb-cli"
export CONTECO_NAME="base"
export CONTECO_TAG="0.7.0"

export CONTECO_BASE="external.ksqldb-cli:0.7.0"
export CONTECO_BUILD="image-base"
