#!/usr/bin/env bash

export CONTECO_LABEL="ksqldb_cli.base - Conteco "
export CONTECO_DESCRIPTION="Confluent ksqlDB CLI base image, using default configuration."

export CONTECO_TYPE="ksqldb_cli"
export CONTECO_NAME="base"
export CONTECO_TAG="0.12.0"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="confluentinc/ksqldb-cli:0.12.0"
