---
version: '3'
services:

# START SERVICE ksqldb-cli.base
  ksqldb-cli:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.ksqldb-cli.base:0.7.0
    environment: []
    command: []
    volumes: []
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_KSQL_CLI_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_KSQL_CLI_DEPLOY_LABELS}]
# END SERVICE ksqldb-cli.base

volumes: {}
networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
